### ISSUE TITLE
Workpiece resolution is insufficient

### ISSUE THREAD

**Issue by ajayre** [CauldronDevelopmentLLC/CAMotics#140] opened 2015-05-18 09:49 UTC
When starting the application for the first time the default units are mm and the default resolution is some strange value like 0.331262. This makes entering the size of the workpiece difficult. The default resolution should make sense for the default units, i.e. 0.1mm.

**Comment by jcoffland** [comment] 2015-05-18 10:48
The resolution you are referring to is automatically calculated based on the size of your tool path.  It's not actually related to the problems with editing the size of the workpiece.  But you are right there is a problem with editing the workpiece size.

**Comment by jcoffland** [comment] 2015-08-23 06:14
Aside from the confusion about what "resolution" means in the app, this is a duplicate of #149.

**Closed by jcoffland** 2015-08-23 06:14 UTC
