### ISSUE TITLE
Libv8 linker errors when building

### ISSUE THREAD

**Issue by yaroslavVl** [CauldronDevelopmentLLC/CAMotics#97] opened 2014-07-08 10:25 UTC
(OS: Ubuntu 10.04 LTS (LinuxCNC) via Oracle Virtual box)
...

    collect2: ld returned 1 exit status
    scons: *** [openscam] Error 1
    scons: building terminated because of errors.

more detail: 
<pre><code>
build_function(["build/build_info.cpp"], [])
g++ -o openscam -Wl,-S -Wl,-x -pthread build/openscam.o build/qrc_openscam.o libOpenSCAM.a libResources.a libclipper.a -L/home/virtmill/v8/lib -L/home/virtmill/v8/lib -L/home/virtmill/openssl-1.0.1f -L/home/virtmill/cbang/lib -lcairo -lv8 -lGLU -lGL -lpng -lz -lfreetype -lcbang -lv8 -lssl -lcrypto -lboost_regex -lboost_filesystem -lboost_system -lboost_iostreams -lsqlite3 -ldl -lexpat -lbz2 -lz -lpthread -lQtOpenGL -lQtGui -lQtCore
libOpenSCAM.a(ToolPathThread.o): In function `OpenSCAM::ToolPathThread::run()':
ToolPathThread.cpp:(.text+0x4e): undefined reference to `v8::Locker::Locker(v8::Isolate*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::symlink(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x3923): undefined reference to `boost::filesystem::detail::create_symlink(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::unlink(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x3b0d): undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::isAbsolute(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x3c94): undefined reference to `boost::filesystem::path::root_directory() const'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::isDirectory(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x3d74): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::exists(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x3f14): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::getFileSize(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x41db): undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::rmdir(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
SystemUtilities.cpp:(.text+0x43f5): undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
SystemUtilities.cpp:(.text+0x4423): undefined reference to `boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::absolute(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x47af): undefined reference to `boost::filesystem::path::root_directory() const'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `T.2189':
SystemUtilities.cpp:(.text+0x4a44): undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::mkdir(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
SystemUtilities.cpp:(.text+0x845f): undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::link(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x8bac): undefined reference to `boost::filesystem::detail::create_hard_link(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(SystemUtilities.o): In function `cb::SystemUtilities::getCanonicalPath(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SystemUtilities.cpp:(.text+0x8de1): undefined reference to `boost::filesystem::detail::system_complete(boost::filesystem::path const&, boost::system::error_code*)'
SystemUtilities.cpp:(.text+0x8e23): undefined reference to `boost::filesystem::path::begin() const'
SystemUtilities.cpp:(.text+0x8e9e): undefined reference to `boost::filesystem::path::m_path_iterator_increment(boost::filesystem::path::iterator&)'
SystemUtilities.cpp:(.text+0x8eca): undefined reference to `boost::filesystem::path::end() const'
SystemUtilities.cpp:(.text+0x8f1d): undefined reference to `boost::filesystem::path::compare(boost::filesystem::path const&) const'
SystemUtilities.cpp:(.text+0x8f62): undefined reference to `boost::filesystem::path::compare(boost::filesystem::path const&) const'
SystemUtilities.cpp:(.text+0x8fa7): undefined reference to `boost::filesystem::path::compare(boost::filesystem::path const&) const'
/home/virtmill/cbang/lib/libcbang.a(Arguments.o): In function `cb::js::Arguments::getCount() const':
Arguments.cpp:(.text+0x49): undefined reference to `v8::Value::FullIsUndefined() const'
/home/virtmill/cbang/lib/libcbang.a(Arguments.o): In function `cb::js::Arguments::has(unsigned int) const':
Arguments.cpp:(.text+0x89): undefined reference to `v8::Value::FullIsUndefined() const'
/home/virtmill/cbang/lib/libcbang.a(Arguments.o): In function `cb::js::Arguments::Arguments(v8::Arguments const&, cb::js::Signature const&)':
Arguments.cpp:(.text+0x367): undefined reference to `v8::Object::GetOwnPropertyNames()'
/home/virtmill/cbang/lib/libcbang.a(Arguments.o): In function `cb::js::Arguments::Arguments(v8::Arguments const&, cb::js::Signature const&)':
Arguments.cpp:(.text+0x7c7): undefined reference to `v8::Object::GetOwnPropertyNames()'
/home/virtmill/cbang/lib/libcbang.a(Arguments.o): In function `cb::js::Arguments::getName(unsigned int) const':
Arguments.cpp:(.text+0x1457): undefined reference to `v8::Value::FullIsUndefined() const'
Arguments.cpp:(.text+0x1b44): undefined reference to `v8::Object::GetOwnPropertyNames()'
/home/virtmill/cbang/lib/libcbang.a(Arguments.o): In function `cb::js::Arguments::has(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
Arguments.cpp:(.text+0x21cf): undefined reference to `v8::Value::FullIsUndefined() const'
/home/virtmill/cbang/lib/libcbang.a(Arguments.o): In function `cb::js::Arguments::get(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
Arguments.cpp:(.text+0x2306): undefined reference to `v8::Value::FullIsUndefined() const'
/home/virtmill/cbang/lib/libcbang.a(Javascript.o): In function `cb::js::Javascript::terminate()':
Javascript.cpp:(.text+0x3e): undefined reference to `v8::V8::TerminateExecution(v8::Isolate*)'
/home/virtmill/cbang/lib/libcbang.a(Script.o): In function `cb::js::Script::load(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Script.cpp:(.text+0x830): undefined reference to `v8::Script::Compile(v8::Handle<v8::String>, v8::Handle<v8::Value>, v8::Handle<v8::String>)'
/home/virtmill/cbang/lib/libcbang.a(Signature.o): In function `cb::js::Signature::toString() const':
Signature.cpp:(.text+0x27d): undefined reference to `v8::Value::FullIsUndefined() const'
/home/virtmill/cbang/lib/libcbang.a(Value.o): In function `cb::js::Value::get(unsigned int) const':
Value.cpp:(.text+0x676): undefined reference to `v8::Object::Get(unsigned int)'
/home/virtmill/cbang/lib/libcbang.a(Value.o): In function `cb::js::Value::get(unsigned int, cb::js::Value) const':
Value.cpp:(.text+0x733): undefined reference to `v8::Object::Get(unsigned int)'
/home/virtmill/cbang/lib/libcbang.a(Value.o): In function `cb::js::Value::length() const':
Value.cpp:(.text+0xa12): undefined reference to `v8::Object::GetOwnPropertyNames()'
/home/virtmill/cbang/lib/libcbang.a(Value.o): In function `cb::js::Value::assertDefined() const':
Value.cpp:(.text+0x1388): undefined reference to `v8::Value::FullIsUndefined() const'
/home/virtmill/cbang/lib/libcbang.a(Value.o): In function `cb::js::Value::assertUint32() const':
Value.cpp:(.text+0x16b8): undefined reference to `v8::Value::IsUint32() const'
/home/virtmill/cbang/lib/libcbang.a(Value.o): In function `cb::js::Value::set(unsigned int, cb::js::Value)':
Value.cpp:(.text+0xdf): undefined reference to `v8::Object::Set(unsigned int, v8::Handle<v8::Value>)'
/home/virtmill/cbang/lib/libcbang.a(Directory.o): In function `cb::Directory::isSubdirectory() const':
Directory.cpp:(.text+0x51): undefined reference to `boost::filesystem::directory_entry::m_get_status(boost::system::error_code*) const'
/home/virtmill/cbang/lib/libcbang.a(Directory.o): In function `cb::Directory::getFilename() const':
Directory.cpp:(.text+0xb2): undefined reference to `boost::filesystem::path::filename() const'
/home/virtmill/cbang/lib/libcbang.a(Directory.o): In function `cb::Directory::next()':
Directory.cpp:(.text+0x17d): undefined reference to `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(Directory.o): In function `cb::Directory::rewind()':
Directory.cpp:(.text+0x295): undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(Directory.o): In function `cb::Directory::Directory(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Directory.cpp:(.text+0x3dc): undefined reference to `boost::filesystem::detail::system_complete(boost::filesystem::path const&, boost::system::error_code*)'
Directory.cpp:(.text+0x4b1): undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
Directory.cpp:(.text+0x4d0): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(Directory.o): In function `cb::Directory::Directory(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Directory.cpp:(.text+0x102c): undefined reference to `boost::filesystem::detail::system_complete(boost::filesystem::path const&, boost::system::error_code*)'
Directory.cpp:(.text+0x1101): undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
Directory.cpp:(.text+0x1120): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/virtmill/cbang/lib/libcbang.a(Subprocess.o): In function `cb::Subprocess::exec(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int, cb::Enumeration<cb::ProcessPriorityEnumeration>)':
Subprocess.cpp:(.text+0x20e7): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(int, boost::iostreams::file_descriptor_flags)'
Subprocess.cpp:(.text+0x2111): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
/home/virtmill/cbang/lib/libcbang.a(Subprocess.o): In function `boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_sink, std::char_traits<char>, std::allocator<char>, boost::iostreams::output_seekable>::open(boost::iostreams::file_descriptor_sink const&, int, int)':
Subprocess.cpp:(.text._ZN5boost9iostreams6detail18indirect_streambufINS0_20file_descriptor_sinkESt11char_traitsIcESaIcENS0_15output_seekableEE4openERKS3_ii[boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_sink, std::char_traits<char>, std::allocator<char>, boost::iostreams::output_seekable>::open(boost::iostreams::file_descriptor_sink const&, int, int)]+0x31): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
Subprocess.cpp:(.text._ZN5boost9iostreams6detail18indirect_streambufINS0_20file_descriptor_sinkESt11char_traitsIcESaIcENS0_15output_seekableEE4openERKS3_ii[boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_sink, std::char_traits<char>, std::allocator<char>, boost::iostreams::output_seekable>::open(boost::iostreams::file_descriptor_sink const&, int, int)]+0x46): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
/home/virtmill/cbang/lib/libcbang.a(Subprocess.o): In function `boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_source, std::char_traits<char>, std::allocator<char>, boost::iostreams::input_seekable>::open(boost::iostreams::file_descriptor_source const&, int, int)':
Subprocess.cpp:(.text._ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_traitsIcESaIcENS0_14input_seekableEE4openERKS3_ii[boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_source, std::char_traits<char>, std::allocator<char>, boost::iostreams::input_seekable>::open(boost::iostreams::file_descriptor_source const&, int, int)]+0x79): undefined reference to `boost::iostreams::file_descriptor_source::file_descriptor_source(boost::iostreams::file_descriptor_source const&)'
Subprocess.cpp:(.text._ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_traitsIcESaIcENS0_14input_seekableEE4openERKS3_ii[boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_source, std::char_traits<char>, std::allocator<char>, boost::iostreams::input_seekable>::open(boost::iostreams::file_descriptor_source const&, int, int)]+0x8b): undefined reference to `boost::iostreams::file_descriptor_source::file_descriptor_source(boost::iostreams::file_descriptor_source const&)'
/home/virtmill/cbang/lib/libcbang.a(Subprocess.o): In function `boost::iostreams::stream<boost::iostreams::file_descriptor_source, std::char_traits<char>, std::allocator<char> >::stream<int, boost::iostreams::file_descriptor_flags>(int&, boost::iostreams::file_descriptor_flags const&, boost::disable_if<boost::is_same<int, boost::iostreams::file_descriptor_source>, void>::type*)':
Subprocess.cpp:(.text._ZN5boost9iostreams6streamINS0_22file_descriptor_sourceESt11char_traitsIcESaIcEEC1IiNS0_21file_descriptor_flagsEEERT_RKT0_PNS_10disable_ifINS_7is_sameIS9_S2_EEvE4typeE[boost::iostreams::stream<boost::iostreams::file_descriptor_source, std::char_traits<char>, std::allocator<char> >::stream<int, boost::iostreams::file_descriptor_flags>(int&, boost::iostreams::file_descriptor_flags const&, boost::disable_if<boost::is_same<int, boost::iostreams::file_descriptor_source>, void>::type*)]+0x12d): undefined reference to `boost::iostreams::file_descriptor_source::file_descriptor_source(int, boost::iostreams::file_descriptor_flags)'
Subprocess.cpp:(.text._ZN5boost9iostreams6streamINS0_22file_descriptor_sourceESt11char_traitsIcESaIcEEC1IiNS0_21file_descriptor_flagsEEERT_RKT0_PNS_10disable_ifINS_7is_sameIS9_S2_EEvE4typeE[boost::iostreams::stream<boost::iostreams::file_descriptor_source, std::char_traits<char>, std::allocator<char> >::stream<int, boost::iostreams::file_descriptor_flags>(int&, boost::iostreams::file_descriptor_flags const&, boost::disable_if<boost::is_same<int, boost::iostreams::file_descriptor_source>, void>::type*)]+0x154): undefined reference to `boost::iostreams::file_descriptor_source::file_descriptor_source(boost::iostreams::file_descriptor_source const&)'
collect2: ld returned 1 exit status
scons: *** [openscam] Error 1
scons: building terminated because of errors.
</code></pre>

**Comment by yaroslavVl** [comment] 2015-01-04 16:53
:'-(((

**Comment by jcoffland** [comment] 2015-01-05 18:38
No luck?

**Comment by yaroslavVl** [comment] 2015-01-06 02:03
still (((
export V8_HOME=/home/virtmill/v8
scons
....
Checking for C library v8... (cached) yes
Checking for C header file pthread.h... yes
Checking for C library pthread... no
Exception: Need library pthread:
  File "/home/virtmill/Desktop/cb1/OpenSCAM/SConstruct", line 48:
    conf.CBConfig('cbang')
  File "/usr/lib/scons/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/home/virtmill/Desktop/cb1/cbang/config/__init__.py", line 166:
    ret = env.cb_methods[name](conf, **kwargs)
  File "/home/virtmill/Desktop/cb1/cbang/config/cbang/__init__.py", line 97:
    conf.CBConfig('cbang-deps', local = False)
  File "/usr/lib/scons/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/home/virtmill/Desktop/cb1/cbang/config/__init__.py", line 166:
    ret = env.cb_methods[name](conf, **kwargs)
  File "/home/virtmill/Desktop/cb1/cbang/config/cbang/__init__.py", line 63:
    else: conf.CBConfig('pthreads')
  File "/usr/lib/scons/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/home/virtmill/Desktop/cb1/cbang/config/__init__.py", line 166:
    ret = env.cb_methods[name](conf, **kwargs)
  File "/home/virtmill/Desktop/cb1/cbang/config/pthreads/__init__.py", line 7:
    conf.CBRequireLib('pthread')
  File "/usr/lib/scons/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/home/virtmill/Desktop/cb1/cbang/config/__init__.py", line 111:
    raise Exception, 'Need library ' + lib

or
scons linkflags=-L/home/virtmill/v8/lib
.....
Checking for C library GL... yes
Checking for C library GLU... yes
Checking for C++ header file v8.h... no
Exception: Need C++ header v8.h:
  File "/home/virtmill/Desktop/cb1/OpenSCAM/SConstruct", line 58:
    conf.CBConfig('v8', True)
  File "/usr/lib/scons/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/home/virtmill/Desktop/cb1/cbang/config/__init__.py", line 166:
    ret = env.cb_methods[name](conf, **kwargs)
  File "/home/virtmill/Desktop/cb1/cbang/config/v8/__init__.py", line 10:
    conf.CBRequireCXXHeader('v8.h')
  File "/usr/lib/scons/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/home/virtmill/Desktop/cb1/cbang/config/__init__.py", line 144:
    raise Exception, 'Need C++ header ' + hdr

It's very difficult for the average user.
But I want to build it. If I can, then all will.

**Comment by jcoffland** [comment] 2015-01-06 03:06
A lot of people are having trouble with the v8 dependency.  I'm working on a general solution.

**Comment by jcoffland** [comment] 2015-10-14 22:51
Have you tried the new version?  It may solve your problem.

**Comment by yaroslavVl** [comment] 2015-10-16 22:50
Of course! Already told friends))) Everything is great! Thanks a lot! However, on my work computer, I see the tool path, but on my home PC - no (both W8.1).
![103](https://cloud.githubusercontent.com/assets/8062959/10554877/59904744-7470-11e5-8568-1b0723f07fef.jpg)
Now there is no need to build from source. But I will try again when i'll have more free time and report the results. Thank you again!

**Comment by jcoffland** [comment] 2015-10-16 23:25
This is caused by #159.  I'm trying to solve this but I don't have the problem on any of my machines.  Have you tried v1.0.3?  It make fix this problem.  Otherwise please add information about your graphics card on #159.

**Comment by jcoffland** [comment] 2016-09-24 23:06
This was fixed by v1.0.5.

**Closed by jcoffland** 2016-09-24 23:06 UTC
Labels: build problem
