### ISSUE TITLE
Simulation error when making a movement that is neither parallel nor perpendicular to the Z axis

### ISSUE THREAD

**Issue by simonemandelli** [CauldronDevelopmentLLC/CAMotics#191] opened 2016-09-20 11:59 UTC
If you try to simulate the attached code , this will produce an erroneous result.
This has been tested with OSX and 10.11.6 Camotics 1.0.6

[cone.txt](https://github.com/CauldronDevelopmentLLC/CAMotics/files/482455/cone.txt)

**Comment by jcoffland** [comment] 2016-09-20 20:41
Perhaps you are seeing this error #173.  It actually works fine in the latest code.  I need to make a release.

![mysnapshot](https://cloud.githubusercontent.com/assets/1166284/18688129/d4348078-7f37-11e6-814a-a58558df5670.png)

I assumed a 4x20mm tool.

**Comment by simonemandelli** [comment] 2016-09-20 22:53
Yes please make a release :-)
Thanks for your great work
Best regards 
Simone

--
Simone Mandelli

**Comment by jcoffland** [comment] 2016-09-24 22:48
Closing this as a duplicate of #173.

**Closed by jcoffland** 2016-09-24 22:48 UTC
Labels: bug, duplicate
