### ISSUE TITLE
CAMotics does not run on Mac

### ISSUE THREAD

**Issue by DougCoffland** [CauldronDevelopmentLLC/CAMotics#269] opened 2018-07-22 01:07 UTC
CAMotics default code does not simulate on Mac. Also, cannot create new tpl program from within CAMotics. And, cannot generate GCode from within CAMotics on Mac.

**Comment by pvgennip** [comment] 2018-08-06 07:59
I have the same problem reloading the camotics.tpl example file (that should load the DXF layer 0), however, the output window said: 
dyld: Library not loaded: QtOpenGL.framework/Versions/4/QtOpenGL
  Referenced from: /Applications/CAMotics.app/Contents/MacOS/tplang
  Reason: image not found

**Comment by jcoffland** [comment] 2019-01-19 11:04
This is a duplicate of #209.

**Closed by jcoffland** 2019-01-19 11:04 UTC
Labels: bug
