### ISSUE TITLE
Rendering issues with real-time simulation.

### ISSUE THREAD

**Issue by hpmachining** [CauldronDevelopmentLLC/CAMotics#264] opened 2018-06-10 22:17 UTC
Rendering looks correct when using "Run", but incorrect when using "Play" button. It is worse the faster you run the simulation. Also, the renderings don't repeat when simulated multiple times (using "Play"). I get similar quality, but deviations differ.

**Run**
![run](https://user-images.githubusercontent.com/19673473/41206025-a54e6e80-6ccb-11e8-9ca7-02bdc7887dae.png)

**Play 1x**
![play_1x](https://user-images.githubusercontent.com/19673473/41206034-a8359b8c-6ccb-11e8-8091-751b6a2c52af.png)

**Play 1x - 2nd example**
![play_1x 2](https://user-images.githubusercontent.com/19673473/41206498-0459fd84-6cd3-11e8-8114-3a42e11766f1.png)

**Play 4x**
![play_4x](https://user-images.githubusercontent.com/19673473/41206036-aa9755dc-6ccb-11e8-9b86-160e53fc3dbf.png)

**System Information:**
Memory: 15.5GiB
Processor: Intel® Core™ i5-8250U CPU @ 1.60GHz × 8
Graphics: Intel® UHD Graphics 620 (Kabylake GT2) 
OS - Arch Linux 64bit with GNOME 3.28.2
CAMotics 1.2.0 commit 5c02a34
V8 3.14.5
Qt 5.11.0

**Comment by jcoffland** [comment] 2018-06-10 23:12
Yes, I was aware of this.  Thanks for opening an issue for it though.  When "Play" is active CAMotics attempts to simulate as the tool moves but the simulation cannot keep up unless the simulation is very simple or the movement slowed way down.  So it attempts to simulate only the area of the workpiece that has changed since the last simulation was run.  Unfortunately, it doesn't always run these localized simulations correctly.  I believe the problem is due to incorrectly calculating the area that needs to be restimulated.

**Comment by hpmachining** [comment] 2018-06-11 14:37
Thank you for the information. I thought it had something to do with not keeping up. I understand that it is a work in progress. Thank you for all you have done with this project. I have been studying the code and hope to learn how you do the simulations, but for now I'm just playing around with the UI. See my [fork](https://github.com/hpmachining/CAMotics) if you are interested in anything I have done.

**Comment by jcoffland** [comment] 2018-06-11 20:16
Awesome, I merged all of your changes.  You may want to resync your fork.

**Comment by jcoffland** [comment] 2019-02-09 10:54
Fixed in new v1.2.0 release.

**Closed by jcoffland** 2019-02-09 10:54 UTC
Labels: bug
