### ISSUE TITLE
Not displaying pcb2gcode or FlatCAM output as expected - bis

### ISSUE THREAD

**Issue by spelle** [CauldronDevelopmentLLC/CAMotics#94] opened 2014-06-11 19:10 UTC
Hello,

I am giving a try to Xubuntu 14.04. And fall in the same case as earlier : the output is not displayed as expected whereas the file used is the same (https://mega.co.nz/#!Z4x0iaLI!0w4WETAtrs4g24lHuSE3kylMqtGLxHoogqFK-WeVA8U)

The thing is that on OpenSCAM 0.11 The result is the same : 
![screenshot - 11062014 - 21 07 26](https://cloud.githubusercontent.com/assets/5351781/3249642/a8a13cac-f19b-11e3-8aa4-da4debf9021d.png)

I then compiled a fresh new version from git. Same result : 
![screenshot - 11062014 - 21 09 29](https://cloud.githubusercontent.com/assets/5351781/3249671/eff1678a-f19b-11e3-9adb-2c7d280abe2d.png)

I don't see the point there.

**Comment by jcoffland** [comment] 2015-01-06 03:08
What happens if you do this before running OpenSCAM?:

    export LC_NUMERIC=C

**Comment by navr32** [comment] 2015-04-28 22:28
Thank's for the reply 
I have same type of problem with openscam package on linux debian testing
and do this before start openscam on terminal 
export LC_NUMERIC=C
well handles my toolpath. could you force this setting in hard on Openscam ?

**Comment by jcoffland** [comment] 2015-04-29 03:09
@navr32 I've done exactly that in the source code.  I just need to make a new release.

**Comment by koppi** [comment] 2015-04-29 22:30
Same issue here:

![screenshot from 2015-04-30 00 28 56](https://cloud.githubusercontent.com/assets/9458631/7402809/fedd3f4e-eecf-11e4-980b-3834c45bd343.png)

vs. with LC_NUMERIC=C

![screenshot from 2015-04-30 00 29 12](https://cloud.githubusercontent.com/assets/9458631/7402814/09780a24-eed0-11e4-9c0f-ffbb1115a959.png)

@navr32 thank's for the workaround.
@jcoffland thank's for the fix.

**Comment by jcoffland** [comment] 2015-08-23 06:26
Duplicate of #100

**Closed by jcoffland** 2015-08-23 06:26 UTC
