### ISSUE TITLE
missing libqt5websockets5 dependency in the .deb file

### ISSUE THREAD

**Issue by fdarling** [CauldronDevelopmentLLC/CAMotics#312] opened 2019-09-23 22:57 UTC
When trying to run camotics after installing using the `camotics_1.2.0_amd64.deb` file, it gives the following missing library error message:

```
$ camotics 
camotics: error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory
```

After installing the missing library:

```
sudo apt-get install libqt5websockets5
```

It launches from the command line as expected and works fine. In the .deb, the dependencies are listed as such:

```
Depends: debconf | debconf-2.0, libc6, libglu1, libv8-3.14.5 | libv8-dev, libglu1-mesa , libqt5core5a, libqt5gui5, libqt5opengl5
```

`libqt5websockets5` should be added to the list to automatically pull in the library during installation.

**Comment by jcoffland** [comment] 2019-09-24 04:26
This is a duplicate of #304.

**Closed by jcoffland** 2019-09-24 04:26 UTC
