### ISSUE TITLE
Incompatible or missing libv8 on newer Linux distributions.

### ISSUE THREAD

**Issue by StevenTyrer** [CauldronDevelopmentLLC/CAMotics#102] opened 2014-09-24 16:32 UTC
Hi I have installed Openscam using the Ubuntu software centre but can not get the program to run from the Terminal or the launcer. can you please help

![image](https://cloud.githubusercontent.com/assets/8901878/4391776/0599a2b4-4408-11e4-8cad-51fd48066b0c.png)

**Edit:**
One solution is to install the ```libv8-dev``` package.  You can install it from your package manger or from the command line like this:

```
sudo apt-get install libv8-dev
```

**Comment by r01walker** [comment] 2015-01-13 06:02
i am running a Debian system with i think the same bug. when i run openscam from a terminal i get.

openscam: error while loading shared libraries: libv8.so.3.14.5: cannot open shared object file: No such file or directory

i Google searched for the file in the Debian back ports downloaded and installed. in terminal when i run openscam i get.

 /lib/i386-linux-gnu/i686/cmov/libm.so.6: version `GLIBC_2.15' not found (required by openscam)

quick google search i find that the glib package is in the experimental debian apt. i was advised in debian blogs to not install it. directly due to my system becoming inoperable or unstable. 

is their any info on building openscam on my system.

i would love to use a cad/cam system. i am considering using a 3d print and a small router or ie air die grinder to clean up the printed part. exporting to the 3d printer a g code from stl, then for the machining export to a dxf or some other format to generate the g code. some of what i will be attempting in processing is what is called Photogrammetry. used to make 3d virtual models.

**Comment by ErichBSchulz** [comment] 2015-06-10 01:47
Hi

I just tried the `sudo apt-get install libv8-dev` trick and alas I'm still getting:

    openscam: error while loading shared libraries: libv8.so.3.14.5: cannot open shared object file: No such file or directory

:-(

**Comment by jcoffland** [comment] 2015-06-15 21:41
@ErichBSchulz your best bet is to try building from source.  The problem is likely that the version of libv8 on your system is different.  I'm working on a better solution for this problem.

**Comment by jcoffland** [comment] 2015-09-21 05:59
Fixed in 1.0.0 release.

**Closed by jcoffland** 2015-09-21 05:59 UTC
Labels: bug, linux

**Comment by silopolis** [comment] 2018-11-15 14:11
Note for others running Testing/Buster while libv8 removed: at the time of writing, installing Sid/Unstable libv8 and libv8-dev packages manually solves the problem and allows v1.1.1 to start.

**Comment by ouinouin** [comment] 2020-04-28 09:32
Hi, unable to find libv8 and libv8-dev in the ubuntu 20.04 repositories either.

**Comment by jcoffland** [comment] 2020-04-28 23:16
@ouinouin Try installing ``node-dev``.

**Comment by jcoffland** [comment] 2020-06-14 21:01
Installing libv8 manually works on Ubuntu 20.04 and possibly others.

    wget http://mirrors.kernel.org/ubuntu/pool/universe/libv/libv8-3.14/libv8-3.14.5_3.14.5.8-5ubuntu2_amd64.deb
    sudo dpkg -i libv8-3.14.5_3.14.5.8-5ubuntu2_amd64.deb
